# config.yaml
dataset:
  path_train: './datasets/SNEMI3D/Train/' # './datasets/MouseCortex/Train/'
  path_test: './datasets/SNEMI3D/Test/'
  channels: 1
  pointCloud_bool: False
  nbr_coords: None 
  aug_0: 3 #nbr of transformations for the images having a 0
  aug_1: 15  #nbr of transformations for the images having a 1
  project_name: 'LSTM_SNEMI' #Name of the project_name to save on wandb
  ckpt_save: './Models/LSTM_CNN/ckptSNEMI/'
  run_name: '1ChannelVolume' # name of the run to save on wandb
  surface : False # take points on the surface only or not 
  big: False

model:
  type: "LSTM_CNN"

training:
  epochs: 200
  lr: 0.0001
  batch: 4
  accumulate_grad_batches: 4

testing:
    treshold: 0.5